<?php /** @var \DavidVerholen\Teaser\Block\Widget\TeaserGroup $block */ ?>
<?php $teaserGroup = $block->getTeaserGroup() ?>
<?php $cssClass = implode(' ', ['row teaserGroup', $teaserGroup->getCssClass()]) ?>
<?php if($block->getData('wrap_with_container')): ?>
<div class="container">
<?php endif;?>
<div class="<?php /** @escapeNotVerified */ echo $cssClass ?>">
    <?php foreach ($teaserGroup->getTeaserItemsCollection() as $teaserItem): ?>
        <?php /** @escapeNotVerified */ echo $block->renderItem($teaserItem) ?>
    <?php endforeach; ?>
</div>
<?php if($block->getData('wrap_with_container')): ?>
    </div>
<?php endif;?>