<?php
/** @var \DavidVerholen\Teaser\Block\Adminhtml\TeaserGroup\AssignTeaserItems $block */
/** @var \DavidVerholen\Teaser\Block\Adminhtml\TeaserGroup\Tab\TeaserItem $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php echo $block->getGridHtml(); ?>
<input type="hidden" name="teaser_group_items" id="in_teaser_group_items" data-form-part="teaser_group_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "DavidVerholen_Teaser/js/teasergroup/edit/assign-teaser-items": {
                "selectedTeaserItems": <?php /* @escapeNotVerified */ echo $block->getTeaserItemsJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
